Repository Tube-Slice/Tube-Slice-BE, pull requests merged in 2024-05, with the labels that each got.

#36 [Feat] 댓글 작성하기 / 삭제하기 구현
  build.gradle
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentController.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentService.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/dto/request/CommentRequestDto.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/keyword/dto/response/KeywordResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/global/response/code/resultCode/ErrorStatus.java
  src/main/java/TubeSlice/tubeSlice/global/response/exception/handler/CommentHandler.java
Labels: :sparkles: 기능

#37 [Feat] 나의 팔로잉 목록 가져오기 / 특정 유저의 팔로잉 목록 가져오기
  src/main/java/TubeSlice/tubeSlice/TubeSliceApplication.java
  src/main/java/TubeSlice/tubeSlice/domain/user/User.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/response/UserResponseDto.java
Labels: :sparkles: 기능

#39 [Feat] 댓글 수정기능 구현
  src/main/java/TubeSlice/tubeSlice/domain/comment/Comment.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentController.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentService.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/dto/request/CommentRequestDto.java
  src/main/java/TubeSlice/tubeSlice/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능

#41 [Feat] 나의 팔로워목록 가져오기 / 특정유저의 팔로워목록 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
Labels: :sparkles: 기능

#43 [Feat] 마이페이지용 유저정보 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/response/UserResponseDto.java
Labels: :sparkles: 기능

#51 [Refactor] 게시글 반환시 생성날짜 포맷 설정
  src/main/java/TubeSlice/tubeSlice/TubeSliceApplication.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/PostResponseDto.java
Labels: :recycle: 리팩터링

#54 [Setting] SSL 인증서 추가 및 CORS 문제 해결
  src/main/java/TubeSlice/tubeSlice/TubeSliceApplication.java
  src/main/resources/ssl/keystore.p12
Labels: 세팅

#58 [Refactor] 로그인 관련 코드 수정
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentController.java
  src/main/java/TubeSlice/tubeSlice/domain/follow/FollowController.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/CustomOauth2User.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/CustomOauth2UserService.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/OAuth2SuccessHandler.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/OAuth2UserInfo.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/OauthService.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/dto/KakaoUserDto.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/dto/NaverUserDto.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/dto/response/OauthResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/postLike/PostLikeController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/global/Jwt/JwtAccessDeniedHandler.java
  src/main/java/TubeSlice/tubeSlice/global/Jwt/JwtAuthenticationEntryPoint.java
  src/main/java/TubeSlice/tubeSlice/global/Jwt/JwtProvider.java
  src/main/java/TubeSlice/tubeSlice/global/Jwt/SecurityUtil.java
  src/main/java/TubeSlice/tubeSlice/global/Jwt/UserDetailsImpl.java
  src/main/java/TubeSlice/tubeSlice/global/Jwt/UserDetailsServiceImpl.java
  src/main/java/TubeSlice/tubeSlice/global/config/CorsConfig.java
  src/main/java/TubeSlice/tubeSlice/global/config/JwtSecurityConfig.java
  src/main/java/TubeSlice/tubeSlice/global/config/SecurityConfig.java
  src/main/java/TubeSlice/tubeSlice/global/config/WebSecurityConfig.java
  src/main/java/TubeSlice/tubeSlice/global/filter/JwtAuthenticationFilter.java
  src/main/java/TubeSlice/tubeSlice/global/provider/JwtProvider.java
  src/main/java/TubeSlice/tubeSlice/global/response/exception/handler/GeneralHandler.java
Labels: :recycle: 리팩터링

#56 [Feat] 나의 키워드 기반 게시글 가져오기 / 특정 유저의 키워드 기반 게시글 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/keyword/KeywordConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/keyword/KeywordRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/oauth/OauthService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/PostResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/postKeyword/PostKeywordRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/response/UserResponseDto.java
  src/main/java/TubeSlice/tubeSlice/global/config/JwtSecurityConfig.java
  src/main/java/TubeSlice/tubeSlice/global/config/WebSecurityConfig.java
  src/main/java/TubeSlice/tubeSlice/global/filter/JwtAuthenticationFilter.java
  src/main/java/TubeSlice/tubeSlice/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/TubeSlice/tubeSlice/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/TubeSlice/tubeSlice/global/jwt/JwtProvider.java
  src/main/java/TubeSlice/tubeSlice/global/jwt/SecurityUtil.java
  src/main/java/TubeSlice/tubeSlice/global/jwt/UserDetailsImpl.java
  src/main/java/TubeSlice/tubeSlice/global/jwt/UserDetailsServiceImpl.java
  src/main/java/TubeSlice/tubeSlice/global/response/code/resultCode/ErrorStatus.java
  src/main/java/TubeSlice/tubeSlice/global/response/exception/handler/KeywordHandler.java
Labels: :sparkles: 기능

#50 [Feat] 스크립트 변환하기 및 요약하기
  .gitignore
  build.gradle
  src/main/java/TubeSlice/tubeSlice/domain/keyword/Keyword.java
  src/main/java/TubeSlice/tubeSlice/domain/script/Script.java
  src/main/java/TubeSlice/tubeSlice/domain/script/ScriptRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/scriptKeyword/ScriptKeyword.java
  src/main/java/TubeSlice/tubeSlice/domain/subtitle/Subtitle.java
  src/main/java/TubeSlice/tubeSlice/domain/text/Text.java
  src/main/java/TubeSlice/tubeSlice/domain/text/TextController.java
  src/main/java/TubeSlice/tubeSlice/domain/text/TextRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/text/TextService.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/request/GptRequest.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/request/SummaryRequestDto.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/request/TextRequestDto.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/response/ClovaSpeechResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/response/GptResponse.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/response/TextResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/video/Video.java
  src/main/java/TubeSlice/tubeSlice/domain/videoKeyword/VideoKeyword.java
  src/main/java/TubeSlice/tubeSlice/global/config/GptConfig.java
  src/main/java/TubeSlice/tubeSlice/global/config/NaverObjectStorageConfig.java
  src/main/resources/application.properties
Labels: :sparkles: 기능

#62 [Feat] 회원정보 수정 구현
  src/main/java/TubeSlice/tubeSlice/domain/user/User.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/request/UserRequestDto.java
Labels: :sparkles: 기능

#65 [Feat] 마이페이지용 특정유저 정보 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/response/UserResponseDto.java
Labels: :sparkles: 기능

#66 [Feat] 게시글 하나의 정보 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/PostResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/response/PostResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/response/UserResponseDto.java
Labels: :sparkles: 기능

#72 [Feat] 게시글의 댓글목록 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/response/PostResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/response/UserResponseDto.java
Labels: :sparkles: 기능

#71 [Feat] 스크립트의 소제목 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/script/ScriptController.java
  src/main/java/TubeSlice/tubeSlice/domain/script/ScriptConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/script/ScriptRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/script/ScriptService.java
  src/main/java/TubeSlice/tubeSlice/domain/script/dto/response/ScriptResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/subtitle/Subtitle.java
  src/main/java/TubeSlice/tubeSlice/domain/subtitle/SubtitleController.java
  src/main/java/TubeSlice/tubeSlice/domain/subtitle/SubtitleRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/subtitle/SubtitleService.java
  src/main/java/TubeSlice/tubeSlice/domain/text/Text.java
  src/main/java/TubeSlice/tubeSlice/domain/text/TextService.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/request/GptRequest.java
  src/main/java/TubeSlice/tubeSlice/domain/text/dto/response/TextResponseDto.java
Labels: :sparkles: 기능

#76 [Feat] 게시판페이지 최신순으로 반환
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/response/PostResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/script/ScriptConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/user/dto/response/UserResponseDto.java
Labels: :sparkles: 기능

#82 [Refactor] 현재페이지 반환 추가
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/response/PostResponseDto.java
Labels: :recycle: 리팩터링

#84 [Feat] 회원탈퇴 구현
  src/main/java/TubeSlice/tubeSlice/domain/user/User.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
Labels: :sparkles: 기능

#88 [Feat] 검색기반 게시판페이지 목록 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/post/Post.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능

#92 [Feat] 게시글 생성/수정/삭제하기
  src/main/java/TubeSlice/tubeSlice/domain/image/ImageServie.java
  src/main/java/TubeSlice/tubeSlice/domain/post/Post.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/request/PostRequestDto.java
  src/main/java/TubeSlice/tubeSlice/domain/postKeyword/PostKeywordRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/postKeyword/PostKeywordService.java
Labels: :sparkles: 기능

#103 [Feat] 프론트 요청 반환값 수정
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentController.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/CommentService.java
  src/main/java/TubeSlice/tubeSlice/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/keyword/KeywordConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/keyword/dto/response/KeywordResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/response/PostResponseDto.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
Labels: :recycle: 리팩터링

#106 [Feat] 마이페이지용 검색어 기반 게시글 목록 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/post/PostRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
Labels: :sparkles: 기능

#108 [Feat] 팔로우 목록에서 닉네임 검색해서 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/user/UserController.java
  src/main/java/TubeSlice/tubeSlice/domain/user/UserService.java
  src/main/java/TubeSlice/tubeSlice/global/response/code/resultCode/ErrorStatus.java
Labels: :sparkles: 기능

#110 [Feat] Timeline 객체 생성
  src/main/java/TubeSlice/tubeSlice/domain/post/Post.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/Timeline.java
Labels: :sparkles: 기능

#116 [Feat] fetch join 추가
  src/main/java/TubeSlice/tubeSlice/domain/post/PostRepository.java
Labels: :recycle: 리팩터링

#117 [Refactor] 게시글 생성하기 수정
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/request/PostRequestDto.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/Timeline.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/TimelineConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/TimelineRepository.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/TimelineService.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/dto/TimelineRequestDto.java
Labels: :recycle: 리팩터링

#120 [Feat] 게시글의 타임라인 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/post/PostController.java
  src/main/java/TubeSlice/tubeSlice/domain/post/PostService.java
  src/main/java/TubeSlice/tubeSlice/domain/post/dto/request/PostRequestDto.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/TimelineConverter.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/TimelineService.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/dto/TimelineRequestDto/TimelineRequestDto.java
  src/main/java/TubeSlice/tubeSlice/domain/timeline/dto/TimelineResponseDto/TimelineResponseDto.java
Labels: :sparkles: 기능

#123 [Fix] 마이페이지에서 게시글 가져오기
  src/main/java/TubeSlice/tubeSlice/domain/post/PostRepository.java
Labels: :recycle: 리팩터링
